name: Setup Theme

on:
  push:
    branches:
      - main

jobs:
  setup-theme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add Ananke theme
      run: |
        git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke
        git add .gitmodules themes/ananke
        git commit -m "Add Ananke theme as submodule"
        git push origin main
